// Copyright (c) 2021 rookie-ninja
//
// Use of this source code is governed by an Apache-style
// license that can be found in the LICENSE file.

// Package rkmuxmeta is a middleware of mux framework for adding metadata in RPC response
package rkmuxmeta

import (
	"context"
	"github.com/gorilla/mux"
	"github.com/rookie-ninja/rk-common/common"
	"github.com/rookie-ninja/rk-entry/entry"
	"github.com/rookie-ninja/rk-mux/interceptor"
	"github.com/rookie-ninja/rk-mux/interceptor/context"
	"net/http"
	"time"
)

// Interceptor will add common headers as extension style in http response.
// The key is defined as bellow:
// 1: X-Request-Id: Request id generated by interceptor.
// 2: X-<Prefix-App: Application name.
// 3: X-<Prefix>-App-Version: Version of application.
// 4: X-<Prefix>-App-Unix-Time: Unix time of current application.
// 5: X-<Prefix>-Request-Received-Time: Time of current request received by application.
func Interceptor(opts ...Option) mux.MiddlewareFunc {
	set := newOptionSet(opts...)

	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(writer http.ResponseWriter, req *http.Request) {
			// wrap writer
			writer = rkmuxinter.WrapResponseWriter(writer)

			req = req.WithContext(context.WithValue(req.Context(), rkmuxinter.RpcEntryNameKey, set.EntryName))

			requestId := rkcommon.GenerateRequestId()
			writer.Header().Set(rkmuxctx.RequestIdKey, requestId)

			event := rkmuxctx.GetEvent(req)
			event.SetRequestId(requestId)
			event.SetEventId(requestId)

			writer.Header().Set(set.AppNameKey, rkentry.GlobalAppCtx.GetAppInfoEntry().AppName)
			writer.Header().Set(set.AppVersionKey, rkentry.GlobalAppCtx.GetAppInfoEntry().Version)

			now := time.Now()
			writer.Header().Set(set.AppUnixTimeKey, now.Format(time.RFC3339Nano))
			writer.Header().Set(set.ReceivedTimeKey, now.Format(time.RFC3339Nano))

			next.ServeHTTP(writer, req)
		})
	}
}
